#!/usr/bin/env bash
# Manages the script manage_my_process.
# when passed the argument 'start':
# 1. Starts manage_my_process
# 2. Create a file containtings its PID in /var/run/my_process.pid
# 3. Display "manage_my_process started"
# when passed the argument 'stop':
# 1. Stops manage_my_process
# 2. Deletes the file /var/run/my_process.pid
# 3. Displays "manage_my_process stopped.pid
# When passes the argument 'restart':
# 1. Stops manage_my_process
# 2. Delete the files /var/run/my_process.pid
# 3. Starts manage_my_process
# 4. Creates a file containing its PID in /var/run/my_process.pid
# 5. Displays "manage_my_process restartes"
# If and other or no aruments are passed, displays
#+ "Usage: manage_my_process {start|stop|restart}"

if [ "$1 == "start" ]
then
./manage_my_process &
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
kill "$(pgrep -f /manage_my_process)"
rm /var/run/my_process.pid
echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then 
kill "$(pgrep -f /manage_my_process)"
rm /var/run/my_process.pid
./manage_my_process &
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"

else
echo "
usage: manage_my_process {start|stop|restart}"
fi
